[[db_servers]]
Name = "Local Postgres"
Type = "postgres"
ConnStringVar = "PG_DBCONN"

[[db_servers]]
Name = "Local MSSQL MusicPlatform"
Type = "sqlserver"
ConnStringVar = "MSSQL_DBCONN"

[[db_servers]]
Name = "Local MySQL"
Type = "mysql"
ConnStringVar = "MySQL_DBCONN"

[[rules]]
Name = "Get Postgres Version"
Description = "Test Postgres"
DbType = "postgres"
Query = """
SELECT version();
"""

[[rules]]
Name = "Get mySql Version"
Description = "Test MySQL"
DbType = "mysql"
Query = """
SELECT version();
"""

[[rules]]
Name = "Get SQL Server Version"
Description = "Test MS SQL Server"
DbType = "sqlserver"
Query = """
SELECT @@version;
"""

[[schedules]]
Server = "Local MSSQL MusicPlatform"
Rule = "Get SQL Server Version"
CronStr = "20,40,59 * * * * *"

[[schedules]]
Server = "Local Postgres"
Rule = "Get Postgres Version"
CronStr = "10,30,50 * * * * *"

[[schedules]]
Server = "Local MySQL"
Rule = "Get mySql Version"
CronStr = "15,35,54 * * * * *"
